# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171223_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='travel_from',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='travel_to',
        ),
    ]
