# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('main', '0003_auto_20180219_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='log_reg.users'),
            preserve_default=False,
        ),
    ]
