# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_travel_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='created_by',
        ),
    ]
