# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('main', '0005_remove_travel_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='user',
        ),
        migrations.AddField(
            model_name='travel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='log_reg.users'),
            preserve_default=False,
        ),
    ]
