# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('main', '0006_auto_20180219_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='user',
            field=models.ManyToManyField(related_name='travels', to='log_reg.users'),
        ),
    ]
