# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_travel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='user',
            new_name='joined_by',
        ),
    ]
