# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180220_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='joined_by',
            field=models.ManyToManyField(related_name='joined', to='log_reg.users'),
        ),
    ]
